name: Check code quality

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  check-code-quality:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --include=dev

      - name: Check code quality
        run: npm run format:check
