name: Cleanup pull request

on:
  pull_request:
    types:
      - closed

permissions:
  contents: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Delete environment
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh api -X DELETE /repos/${{ github.repository }}/environments/pr-${{ github.event.pull_request.number }}

      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: Remove PR folder from gh-pages
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git rm -r --ignore-unmatch pr-${{ github.event.pull_request.number }}
          if git commit -m "Remove pr-${{ github.event.pull_request.number }}"; then
            git push
          fi
